### ISSUE TITLE
Make board history scrollable

### ISSUE THREAD

**Issue by Ajetski** [Ajetski/Chess-App-Api#10]
**Describe the bug**
When playing a game with > 20 moves, the pgn goes off the end of the board history component

**To Reproduce**
1. Start a game
2. Play more than 20 moves
3. Look at the game history panel on the right side of the screen

**Expected behavior**
We should make that component scrollable

**Screenshots**
![Capture.PNG](https://images.zenhubusercontent.com/5f33fd967c7c83450ee69fb6/1c2f346e-7fb1-4905-934f-b32eb9c25242)

**Environment (please complete the following information):**
 - Chrome

**Comment by calebGarrick** [comment]
This issue should be in Chess-App

**Comment by calebGarrick** [comment]
Issue moved to [Ajetski/Chess-App #41](https://github.com/Ajetski/Chess-App/issues/41) via [**ZenHub**](https://www.zenhub.com/)
